[package]

name = "http-rs"
version = "0.0.1"
authors = [ "Pierre-Henri Symoneaux" ]
license = "BSD-3-Clause"

[dependencies]
openssl = "*"

[[bin]]
name = "http-rs"

[lib]
name = "http"
